# Generated by Django 3.2.8 on 2022-05-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
