# Generated by Django 3.2.13 on 2022-05-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_patronymic_employee_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hierarchy_level',
            field=models.IntegerField(default=5),
        ),
    ]
